# Generated by Django 5.0.7 on 2025-05-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_student_class_student_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='registration_number',
        ),
    ]
