# Generated by Django 5.0.7 on 2025-05-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_phone_number_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
